spring:
  application:
    name: cafe-management

  datasource:
    url: jdbc:mysql://localhost:3306/cafedb
    username: root
    password: "****"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "**************"
    password: "*********"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8081

logging:
  file:
    path: logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    web: error
    root: info
    sql: error


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true



